In [ ]:
from data_ingestion import loading_data
from data_cleaning import remove_card_info, remove_name_info 
import pandas as pd

In [ ]:

data = loading_data()
no_card = remove_card_info(data)
no_name = remove_name_info(no_card)
df = pd.DataFrame(no_name)
df.head()

,date_time,location,order,total_price,payment_method
0,05/09/2023 09:00,Leeds,"Regular Iced americano - 2.15, Large Hot Choco...",7.8,CARD
1,05/09/2023 09:01,Leeds,"Large Chai latte - 2.60, Regular Hot Chocolate...",4,CASH
2,05/09/2023 09:03,Leeds,"Regular Chai latte - 2.30, Regular Filter coff...",6.4,CARD
3,05/09/2023 09:04,Leeds,"Regular Iced americano - 2.15, Regular Hot Cho...",3.55,CARD
4,05/09/2023 09:06,Leeds,Large Speciality Tea - English breakfast - 1.6...,4.4,CASH

In [ ]:
df['payment_method']

0     CARD
1     CASH
2     CARD
3     CARD
4     CASH
5     CARD
6     CARD
7     CASH
8     CARD
9     CARD
10    CASH
11    CASH
12    CARD
13    CARD
14    CARD
15    CARD
16    CARD
17    CASH
18    CARD
19    CASH
20    CARD
21    CARD
22    CARD
23    CASH
24    CARD
25    CARD
26    CARD
27    CASH
28    CASH
29    CARD
30    CARD
31    CARD
32    CARD
33    CASH
34    CARD
35    CASH
36    CARD
37    CARD
38    CARD
39    CASH
40    CASH
41    CASH
42    CARD
43    CARD
44    CASH
45    CARD
46    CARD
47    CARD
48    CARD
49    CASH
Name: payment_method, dtype: object